services:
  - name: app
    env:
      - REDIS_HOST: $REDIS_HOST
      - REDIS_PORT: $REDIS_PORT
      - REDIS_PASSWORD: $REDIS_PASSWORD
      - PG_HOST: $PG_HOST
      - PG_PORT: $PG_PORT
      - PG_USER: $PG_USER
      - PG_PASSWORD: $PG_PASSWORD
      - PG_DATABASE: $PG_DATABASE
    env_files:
      - .env
    build:
      context: ./src
      dockerfile: Dockerfile
    start_command: npm start
    ports:
      - 8080:8000
    dependencies:
      - service: postgres
      - service: cache

  - name: postgres
    plan: starter
    env:
      - POSTGRES_DB: $PG_DATABASE
      - POSTGRES_USER: $PG_USER
      - POSTGRES_PASSWORD: $PG_PASSWORD

  - name: cache
    plan: starter
    env:
      - REDIS_PASSWORD: $REDIS_PASSWORD
    dependencies: []

volumes:
  - name: cache
    plan: starter
